/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all channels
         * @description Returns a list of all channels
         */
        get: operations["listChannels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Channel: {
            /**
             * Format: uuid
             * @description Unique identifier for the channel
             */
            id: string;
            /** @description Title of the channel */
            title: string;
            /** @description EPG ID for electronic program guide information */
            guide_id: string;
            /** @description URL to the channel logo image */
            logo?: string;
            /** @description Category/group of the channel (e.g., Sports, Movies, News) */
            group_title: string;
            /** @description Available streams for this channel */
            streams: components["schemas"]["Stream"][];
        };
        Stream: {
            /**
             * Format: uuid
             * @description Unique identifier for the stream
             */
            id: string;
            /**
             * Format: uuid
             * @description ID of the parent channel
             */
            channel_id: string;
            /** @description Acestream ID for this stream */
            acestream_id: string;
            /** @description Quality of the stream (e.g., SD, HD, FHD) */
            quality?: string;
            /** @description Tags associated with this stream */
            tags?: string[];
            /** @description Network caching value in milliseconds */
            network_caching: number;
        };
        Error: {
            /** @description Error message */
            message?: string;
            /** @description Error code */
            code?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"][];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
