# .golangci.yml
# golangci-lint configuration for IPTV Manager

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - goconst
    - gocyclo
    - misspell
    - unparam
    - unconvert
    - goimports
    - revive

linters-settings:
  gofmt:
    simplify: true
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor
    - .direnv
    - web-ui

run:
  timeout: 5m
  tests: true
