//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Channel Read-only channel view derived from streams grouped by guide_id and enriched with EPG metadata
type Channel struct {
	// GroupTitle Category/group of the channel (from EPG or manual)
	GroupTitle *string `json:"group_title,omitempty"`

	// GuideId EPG ID for electronic program guide information (grouping key)
	GuideId string `json:"guide_id"`

	// Logo URL to the channel logo image (from EPG)
	Logo *string `json:"logo,omitempty"`

	// Streams Available streams for this channel
	Streams *[]Stream `json:"streams,omitempty"`

	// Title Title of the channel (from EPG)
	Title *string `json:"title,omitempty"`
}

// EPGChannel defines model for EPGChannel.
type EPGChannel struct {
	// Id EPG channel identifier (e.g., dazn.f1.hd)
	Id string `json:"id"`

	// Logo URL to the channel logo from EPG
	Logo *string `json:"logo,omitempty"`

	// Name Display name of the channel
	Name string `json:"name"`
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code *int `json:"code,omitempty"`

	// Message Error message
	Message *string `json:"message,omitempty"`
}

// Stream Primary entity representing a single Acestream source
type Stream struct {
	// AcestreamId Acestream ID for this stream
	AcestreamId string `json:"acestream_id"`

	// GuideId EPG ID that groups this stream into a channel
	GuideId string `json:"guide_id"`

	// Id Unique identifier for the stream
	Id *openapi_types.UUID `json:"id,omitempty"`

	// NetworkCaching Network caching value in milliseconds
	NetworkCaching int `json:"network_caching"`

	// Quality Quality of the stream (e.g., SD, HD, FHD)
	Quality *string `json:"quality,omitempty"`

	// Tags Tags associated with this stream
	Tags *[]string `json:"tags,omitempty"`
}

// ListEPGChannelsParams defines parameters for ListEPGChannels.
type ListEPGChannelsParams struct {
	// Search Search query to filter channels by name or ID
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// CreateStreamJSONRequestBody defines body for CreateStream for application/json ContentType.
type CreateStreamJSONRequestBody = Stream

// UpdateStreamJSONRequestBody defines body for UpdateStream for application/json ContentType.
type UpdateStreamJSONRequestBody = Stream

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all channel views
	// (GET /channels)
	ListChannels(w http.ResponseWriter, r *http.Request)
	// Get a channel view by guide_id
	// (GET /channels/{guide_id})
	GetChannelByGuideId(w http.ResponseWriter, r *http.Request, guideId string)
	// List all EPG channels
	// (GET /epg/channels)
	ListEPGChannels(w http.ResponseWriter, r *http.Request, params ListEPGChannelsParams)
	// List all streams
	// (GET /streams)
	ListStreams(w http.ResponseWriter, r *http.Request)
	// Create a new stream
	// (POST /streams)
	CreateStream(w http.ResponseWriter, r *http.Request)
	// Delete a stream
	// (DELETE /streams/{id})
	DeleteStream(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get a stream by ID
	// (GET /streams/{id})
	GetStream(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update a stream
	// (PUT /streams/{id})
	UpdateStream(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListChannels operation middleware
func (siw *ServerInterfaceWrapper) ListChannels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChannels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChannelByGuideId operation middleware
func (siw *ServerInterfaceWrapper) GetChannelByGuideId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "guide_id" -------------
	var guideId string

	err = runtime.BindStyledParameterWithOptions("simple", "guide_id", r.PathValue("guide_id"), &guideId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "guide_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChannelByGuideId(w, r, guideId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEPGChannels operation middleware
func (siw *ServerInterfaceWrapper) ListEPGChannels(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEPGChannelsParams

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", r.URL.Query(), &params.Search)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEPGChannels(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListStreams operation middleware
func (siw *ServerInterfaceWrapper) ListStreams(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListStreams(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateStream operation middleware
func (siw *ServerInterfaceWrapper) CreateStream(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateStream(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteStream operation middleware
func (siw *ServerInterfaceWrapper) DeleteStream(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteStream(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStream operation middleware
func (siw *ServerInterfaceWrapper) GetStream(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStream(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateStream operation middleware
func (siw *ServerInterfaceWrapper) UpdateStream(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateStream(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/channels", wrapper.ListChannels)
	m.HandleFunc("GET "+options.BaseURL+"/channels/{guide_id}", wrapper.GetChannelByGuideId)
	m.HandleFunc("GET "+options.BaseURL+"/epg/channels", wrapper.ListEPGChannels)
	m.HandleFunc("GET "+options.BaseURL+"/streams", wrapper.ListStreams)
	m.HandleFunc("POST "+options.BaseURL+"/streams", wrapper.CreateStream)
	m.HandleFunc("DELETE "+options.BaseURL+"/streams/{id}", wrapper.DeleteStream)
	m.HandleFunc("GET "+options.BaseURL+"/streams/{id}", wrapper.GetStream)
	m.HandleFunc("PUT "+options.BaseURL+"/streams/{id}", wrapper.UpdateStream)

	return m
}

type ListChannelsRequestObject struct {
}

type ListChannelsResponseObject interface {
	VisitListChannelsResponse(w http.ResponseWriter) error
}

type ListChannels200JSONResponse []Channel

func (response ListChannels200JSONResponse) VisitListChannelsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListChannels500JSONResponse Error

func (response ListChannels500JSONResponse) VisitListChannelsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetChannelByGuideIdRequestObject struct {
	GuideId string `json:"guide_id"`
}

type GetChannelByGuideIdResponseObject interface {
	VisitGetChannelByGuideIdResponse(w http.ResponseWriter) error
}

type GetChannelByGuideId200JSONResponse Channel

func (response GetChannelByGuideId200JSONResponse) VisitGetChannelByGuideIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetChannelByGuideId404JSONResponse Error

func (response GetChannelByGuideId404JSONResponse) VisitGetChannelByGuideIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetChannelByGuideId500JSONResponse Error

func (response GetChannelByGuideId500JSONResponse) VisitGetChannelByGuideIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListEPGChannelsRequestObject struct {
	Params ListEPGChannelsParams
}

type ListEPGChannelsResponseObject interface {
	VisitListEPGChannelsResponse(w http.ResponseWriter) error
}

type ListEPGChannels200JSONResponse []EPGChannel

func (response ListEPGChannels200JSONResponse) VisitListEPGChannelsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListEPGChannels500JSONResponse Error

func (response ListEPGChannels500JSONResponse) VisitListEPGChannelsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListStreamsRequestObject struct {
}

type ListStreamsResponseObject interface {
	VisitListStreamsResponse(w http.ResponseWriter) error
}

type ListStreams200JSONResponse []Stream

func (response ListStreams200JSONResponse) VisitListStreamsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListStreams500JSONResponse Error

func (response ListStreams500JSONResponse) VisitListStreamsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateStreamRequestObject struct {
	Body *CreateStreamJSONRequestBody
}

type CreateStreamResponseObject interface {
	VisitCreateStreamResponse(w http.ResponseWriter) error
}

type CreateStream201JSONResponse Stream

func (response CreateStream201JSONResponse) VisitCreateStreamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateStream400JSONResponse Error

func (response CreateStream400JSONResponse) VisitCreateStreamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateStream500JSONResponse Error

func (response CreateStream500JSONResponse) VisitCreateStreamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteStreamRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteStreamResponseObject interface {
	VisitDeleteStreamResponse(w http.ResponseWriter) error
}

type DeleteStream204Response struct {
}

func (response DeleteStream204Response) VisitDeleteStreamResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteStream404JSONResponse Error

func (response DeleteStream404JSONResponse) VisitDeleteStreamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteStream500JSONResponse Error

func (response DeleteStream500JSONResponse) VisitDeleteStreamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetStreamRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetStreamResponseObject interface {
	VisitGetStreamResponse(w http.ResponseWriter) error
}

type GetStream200JSONResponse Stream

func (response GetStream200JSONResponse) VisitGetStreamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetStream404JSONResponse Error

func (response GetStream404JSONResponse) VisitGetStreamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetStream500JSONResponse Error

func (response GetStream500JSONResponse) VisitGetStreamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateStreamRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateStreamJSONRequestBody
}

type UpdateStreamResponseObject interface {
	VisitUpdateStreamResponse(w http.ResponseWriter) error
}

type UpdateStream200JSONResponse Stream

func (response UpdateStream200JSONResponse) VisitUpdateStreamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateStream400JSONResponse Error

func (response UpdateStream400JSONResponse) VisitUpdateStreamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateStream404JSONResponse Error

func (response UpdateStream404JSONResponse) VisitUpdateStreamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateStream500JSONResponse Error

func (response UpdateStream500JSONResponse) VisitUpdateStreamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all channel views
	// (GET /channels)
	ListChannels(ctx context.Context, request ListChannelsRequestObject) (ListChannelsResponseObject, error)
	// Get a channel view by guide_id
	// (GET /channels/{guide_id})
	GetChannelByGuideId(ctx context.Context, request GetChannelByGuideIdRequestObject) (GetChannelByGuideIdResponseObject, error)
	// List all EPG channels
	// (GET /epg/channels)
	ListEPGChannels(ctx context.Context, request ListEPGChannelsRequestObject) (ListEPGChannelsResponseObject, error)
	// List all streams
	// (GET /streams)
	ListStreams(ctx context.Context, request ListStreamsRequestObject) (ListStreamsResponseObject, error)
	// Create a new stream
	// (POST /streams)
	CreateStream(ctx context.Context, request CreateStreamRequestObject) (CreateStreamResponseObject, error)
	// Delete a stream
	// (DELETE /streams/{id})
	DeleteStream(ctx context.Context, request DeleteStreamRequestObject) (DeleteStreamResponseObject, error)
	// Get a stream by ID
	// (GET /streams/{id})
	GetStream(ctx context.Context, request GetStreamRequestObject) (GetStreamResponseObject, error)
	// Update a stream
	// (PUT /streams/{id})
	UpdateStream(ctx context.Context, request UpdateStreamRequestObject) (UpdateStreamResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListChannels operation middleware
func (sh *strictHandler) ListChannels(w http.ResponseWriter, r *http.Request) {
	var request ListChannelsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListChannels(ctx, request.(ListChannelsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListChannels")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListChannelsResponseObject); ok {
		if err := validResponse.VisitListChannelsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetChannelByGuideId operation middleware
func (sh *strictHandler) GetChannelByGuideId(w http.ResponseWriter, r *http.Request, guideId string) {
	var request GetChannelByGuideIdRequestObject

	request.GuideId = guideId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetChannelByGuideId(ctx, request.(GetChannelByGuideIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetChannelByGuideId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetChannelByGuideIdResponseObject); ok {
		if err := validResponse.VisitGetChannelByGuideIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListEPGChannels operation middleware
func (sh *strictHandler) ListEPGChannels(w http.ResponseWriter, r *http.Request, params ListEPGChannelsParams) {
	var request ListEPGChannelsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListEPGChannels(ctx, request.(ListEPGChannelsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListEPGChannels")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListEPGChannelsResponseObject); ok {
		if err := validResponse.VisitListEPGChannelsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListStreams operation middleware
func (sh *strictHandler) ListStreams(w http.ResponseWriter, r *http.Request) {
	var request ListStreamsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListStreams(ctx, request.(ListStreamsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListStreams")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListStreamsResponseObject); ok {
		if err := validResponse.VisitListStreamsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateStream operation middleware
func (sh *strictHandler) CreateStream(w http.ResponseWriter, r *http.Request) {
	var request CreateStreamRequestObject

	var body CreateStreamJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateStream(ctx, request.(CreateStreamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateStream")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateStreamResponseObject); ok {
		if err := validResponse.VisitCreateStreamResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteStream operation middleware
func (sh *strictHandler) DeleteStream(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteStreamRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteStream(ctx, request.(DeleteStreamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteStream")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteStreamResponseObject); ok {
		if err := validResponse.VisitDeleteStreamResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStream operation middleware
func (sh *strictHandler) GetStream(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetStreamRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStream(ctx, request.(GetStreamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStream")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStreamResponseObject); ok {
		if err := validResponse.VisitGetStreamResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateStream operation middleware
func (sh *strictHandler) UpdateStream(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateStreamRequestObject

	request.Id = id

	var body UpdateStreamJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateStream(ctx, request.(UpdateStreamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateStream")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateStreamResponseObject); ok {
		if err := validResponse.VisitUpdateStreamResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RZXW/buBL9KwPe++AL6NruxwUKv7Vxb2qg3Wab5qkIiok0ltlSpEJSzmoD//cFSX3Z",
	"khN326Te3TdbImdGc86cGUq3LFZZriRJa9jslpl4RRn6nycrlJKE+5mQiTXPLVeSzdgHwuS/SooS4rAE",
	"1pxuICHN15TAUqsMjNWEmYFUqyKnBK5KSAue0GeeAMoESGoeryiBG25X8PrsFDKymKBFFrFcq5y05eTj",
	"8CY+W24F9WM5QUup0uXErwK1BLuiJq6Rj8VZVxoylAWK/7CIacLkvRQlm1ldUMRsmRObMWM1lynbRKwO",
	"te/P2VrMYak0kKDYaiV5DLlWqcYsPCJwuVQ6Q7cDRj4uLlP4SqXz3fMlVKr6fi4+vAWrth7GLQSeYUrt",
	"cx30NBUWfScv18gFXglq4HLPZVfc1E5ZxLilsPffmpZsxv41aRkzqegyOff7nbM90aDWWLr7e3D86C7v",
	"he+Ax/SurwuuKWGzTy2Ctcdoi0dtUi4bS+rqC8XWxfj67LRD/m027iNFHTNPSFq+5KRhRON0HEGCv8vx",
	"8sl4lfwA/OuMDFmSmA1kds5NLrAEd3cnwey+LPr8ebODadJa6X6GYpUMhOEXg7/XmOLSUkra2crIGEz3",
	"7qtvDwXci6siY8/UmeYZ6hIcQLYETbkm4/7IFBAMl6kgeBlToAYYVeiYenKE9YJBfWi3VyrhqylcYn9G",
	"aewKbVBR07UFXFoFuB/JaJCpF5JfF9QlaYiR2hCDdrEZKwoP/73yIsneKP31c4zxyl3qOf0lLIBqAaxR",
	"uBgkZFwIbihWMjGDrLguUHBb9k3+Gm7UfK5yUhXc+TyCN/MI/v9mPlhxFtMBMfyIqQE0RsUcbd2YttFr",
	"pLBvckvldqpoizFRV5p2U9evMmfL9ZNQWNJibN3PUOodtr1DiVXSdgh5tvAYZ26By367p+KO8Q05JUka",
	"fS28e3YBTjIEN9Y0AjrgDV6eLVjE1qRNcPZ0PB1PXQwqJ4k5ZzP2bDwdP3NFhHblczep3freTnZovrCF",
	"lgYQXAQOYxSijXZ06KDhwHeV6zvxImEz9pYbe1K7dyCZXEkT6vrpdFonmaSPCvNc8NjvnnwxLrR6PvKN",
	"4JC+WLeRPkV6QJ0XcUzGLAsBTdBu3/++Ma67wgmKPeSc9Jo0UHU/YqbInFZWOesC4Ic9TwtfRp9Yg+el",
	"29jAO7mtcdgcgHSlvlsD5eiuIbI3N/bRPqUa7Fflqdu3SDwRNWZkSbvgh0Q3DHGLuSt4d80xt26Ds271",
	"tjUelLHFYLdJXX4n1w6i2OGUej59/vCUquICqSwsVSETGEnVlGurrm21HgHZT8m2TTWwsEO6/aSnPP1u",
	"XcNmGufSd7WGjIM61g6p5j5WnxPqeAXXBenSTZVLLizp1vNVPR3qDu396pb3xttgD8nygxS1M5v/HUS1",
	"c3ToairlacWszuHtG0hV7xoiznlz7+HRas+Ff3mk2pTWIDVHyE3EcmUGwDnRhJYcOJJuKgtjOOnKCzeA",
	"hVUZWh6jEGX9GmXcwy4YO6+HUdd9yNhXKil/WIJquLYnWNfdNj22PHkQrzu4VIOqf/IETMMRUYY+9gjc",
	"WMg1Cp4Al3lhj4GRgQdbnBokZUc9JrfVFJaQIDv0ksBf94NYSPlVCYv5fVQt8sTh0qdqMNdQ9e7mVB+X",
	"h+eteyat3dPq/T3pef/pqxBCcoZo9gjjUhVDMy0dA9MCjA0p9kjfYZN9Y6I3ox8nTaaPIW8/cz4/RsKF",
	"8bsrQfvabTHAuQsvRwZQAv3GjX+XcVjP3StkweTRMPTndvzp43X8CpAj6fj/2HoM9L+7Afgd3sRQUbxV",
	"MQpIaE1C5RlJC2Eti1ihBZuxlbX5bDIRbt1KGTt7MX0xnWDOmaN85W7/F8imXMO3q613VN/2prAq0+Yw",
	"tol60/yHi/muw9roKN/6uNAxWGeqb+99a0qT8Hy3yp8IR6/bb4tn1bdF/warY9cdETeXmz8CAAD//9pa",
	"6XzBHQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
