//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Channel defines model for Channel.
type Channel struct {
	// GroupTitle Category/group of the channel (e.g., Sports, Movies, News)
	GroupTitle string `json:"group_title"`

	// GuideId EPG ID for electronic program guide information
	GuideId string `json:"guide_id"`

	// Id Unique identifier for the channel
	Id openapi_types.UUID `json:"id"`

	// Logo URL to the channel logo image
	Logo *string `json:"logo,omitempty"`

	// Streams Available streams for this channel
	Streams []Stream `json:"streams"`

	// Title Title of the channel
	Title string `json:"title"`
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code *int `json:"code,omitempty"`

	// Message Error message
	Message *string `json:"message,omitempty"`
}

// Stream defines model for Stream.
type Stream struct {
	// AcestreamId Acestream ID for this stream
	AcestreamId string `json:"acestream_id"`

	// ChannelId ID of the parent channel
	ChannelId openapi_types.UUID `json:"channel_id"`

	// Id Unique identifier for the stream
	Id openapi_types.UUID `json:"id"`

	// NetworkCaching Network caching value in milliseconds
	NetworkCaching int `json:"network_caching"`

	// Quality Quality of the stream (e.g., SD, HD, FHD)
	Quality *string `json:"quality,omitempty"`

	// Tags Tags associated with this stream
	Tags *[]string `json:"tags,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all channels
	// (GET /channels)
	ListChannels(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListChannels operation middleware
func (siw *ServerInterfaceWrapper) ListChannels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChannels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/channels", wrapper.ListChannels)

	return m
}

type ListChannelsRequestObject struct {
}

type ListChannelsResponseObject interface {
	VisitListChannelsResponse(w http.ResponseWriter) error
}

type ListChannels200JSONResponse []Channel

func (response ListChannels200JSONResponse) VisitListChannelsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListChannels500JSONResponse Error

func (response ListChannels500JSONResponse) VisitListChannelsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all channels
	// (GET /channels)
	ListChannels(ctx context.Context, request ListChannelsRequestObject) (ListChannelsResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListChannels operation middleware
func (sh *strictHandler) ListChannels(w http.ResponseWriter, r *http.Request) {
	var request ListChannelsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListChannels(ctx, request.(ListChannelsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListChannels")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListChannelsResponseObject); ok {
		if err := validResponse.VisitListChannelsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/5RV32/bNhD+Vw63PWyAYBsNBhR6C5JuNZB0WdM+FUHAUmeZHUUyx5MDo/D/PpD6EdvS",
	"tuZN4t199+n77qjvqH0TvCMnEcvvGPWWGpUfr7bKObLpMbAPxGIoB2r2bXgUI5bSa0VRswlivMMSr5RQ",
	"7Xm/zFngNyBbAt1hwS+0qBcF3AfPEgu49TtDsYAP9Bx/xQJlHwhLjMLG1XgosG5NRY+mmvZ5d/cHrK9h",
	"4xnIkhb2zmgI7GtWDeQ6MG7juVG5YgZ8DvazM08tganIidkY4tzh6BOwwA4US2xbU80BW1/7GeiPNyD+",
	"RI6UCKZRNc3BRGFSTZwiXe6UseqrJehTepImHrE0Ql3tz0wbLPGn5YvTy97m5X2uT8367opZ7fP7vL2f",
	"0vGZq1PuhwKZnlrDVGH5BTuVMuCRpcXJIL187sMI579+Iy2JzTtmz9NJ1L6a4ZiTIcdGKOOEauKE1VCM",
	"SfF/qRvCcx814dXrNyGmNHWfMzu7l0N0mOBsXXc0Nwi9zrNY6+vBjaCYnLxmTl+3ACO//8V1JM+e/37U",
	"Sm/T0aTJhy4B+gTYKZt6OmiMtSaS9q6Ks+Y9tcoa2U8h/+oCgxi9vsN9c13A++sCfn9/PXvNiKpn1uyT",
	"qiOoGL02SqiCZyPbM6vGJZtCnuzT3EIcuVqcDsxUwelOJMh0v3Vr4ERpSY9ONXQyYbfKqV67syG8W2dr",
	"m5SQTHip6ZlFUK6CmhyxkpRxe/EZglV7a6LEcaVnusHl3RoL3BHHrtmbxWqxShx8IKeCwRIvFqvFBRYY",
	"lGyzhMuhbf7HkEwN+UjSsougIDFIVitrR7aY0Tlf9+sKS7wxUa5egkwxeBe7BX2zWg3KkcutVAjW6Fy9",
	"/BZTv+FvmJ5+6DYd/phT+yfq37daU4yb1sJIOtX99kpe/0WnuzTnmhPviIH6eIGxbRrF+16zc1W77fiC",
	"49FDxowZJUXOfbrxWlmoaEfWhyZdSl0uFtiyxRK3IqFcLm3K2/oo5dvV29UyzcXhYex3jvrnoFMEJps3",
	"Uvwxz372x5PDw+GfAAAA//+pN7eb3wgAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
